services:
  publisher-frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - pubslisher-api
    networks:
      - caddy_net
    restart: unless-stopped

  pubslisher-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - badger_data:/app/data
    environment:
      - GIN_MODE=release
    networks:
      - caddy_net
    restart: unless-stopped

networks:
  caddy_net:
    external: true

volumes:
  badger_data:
    driver: local
